name: Test and Typecheck

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Run all tests
    runs-on: ubuntu-latest
    container: oven/bun:1.2.1
    steps:
      - uses: actions/checkout@v4
      - run: bun install
      - run: bun test
      - run: bun typecheck
